name: lagranto
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_4
  - backports.functools_lru_cache=2.0.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - brotli-python=1.0.9=py37hd23a5d3_7
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cartopy=0.20.2=py37h9a08e6e_0
  - cdo=2.0.3=h34154eb_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.1=py37h43b0acd_1
  - chardet=5.0.0=py37h89c1867_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=22.9.0=py37h89c1867_1
  - conda-build=3.22.0=py37h89c1867_2
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.11.0=pyhd8ed1ab_0
  - cryptography=38.0.2=py37h5994e8b_1
  - curl=8.8.0=he654da7_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.3=py37hd23a5d3_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - eccodes=2.26.0=hc08acdf_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - filelock=3.16.1=pyhd8ed1ab_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.12.1=h267a509_2
  - geos=3.10.1=h9c3ff4c_1
  - glob2=0.7=py_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.1=nompi_h4df4325_104
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - importlib_resources=6.0.0=pyhd8ed1ab_0
  - ipykernel=6.16.2=pyh210e3f2_0
  - ipython=7.33.0=py37h89c1867_0
  - jasper=2.0.33=h0ff4b12_1
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py37h89c1867_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.4=py37h7cecad7_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.7.4=hfca40fe_0
  - libblas=3.9.0=20_linux64_openblas
  - libcblas=3.9.0=20_linux64_openblas
  - libcurl=8.8.0=hca28451_1
  - libdeflate=1.14=h166bdaf_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.2.0=h767d61c_6
  - libgcc-ng=15.2.0=h69a702a_6
  - libgfortran=15.2.0=h69a702a_6
  - libgfortran-ng=15.2.0=h69a702a_6
  - libgfortran5=15.2.0=hcd61629_6
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_6
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=20_linux64_openblas
  - liblief=0.12.2=h27087fc_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnetcdf=4.8.1=nompi_h329d8a1_102
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libpng=1.6.43=h2797004_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=15.2.0=h8f9b012_6
  - libstdcxx-ng=15.2.0=h4852527_6
  - libtiff=4.4.0=h82bc61c_5
  - libudunits2=2.2.28=h40f5838_3
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.12.7=hc051c1a_1
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=h4ab18f5_6
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h280c20c_1002
  - markupsafe=2.1.1=py37h540881e_1
  - matplotlib-base=3.3.2=py37h4f6019d_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - metpy=1.2.0=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=1.21.6=py37h976b520_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.5.4=h26f9b46_0
  - ossuuid=1.6.2=h5888daf_1001
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=1.2.3=py37hdc94413_0
  - parso=0.8.4=pyhd8ed1ab_0
  - patch=2.8=hb03c661_1002
  - patchelf=0.17.2=h58526e2_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py37h850a105_2
  - pint=0.18=pyhd8ed1ab_0
  - pip=24.0=pyhd8ed1ab_0
  - pkginfo=1.10.0=pyhd8ed1ab_0
  - platformdirs=4.0.0=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - proj=8.2.0=h277dcde_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=5.9.3=py37h540881e_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py-lief=0.12.2=py37hd23a5d3_0
  - pycosat=0.6.4=py37h540881e_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyproj=3.2.1=py37hb589d83_5
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py37h89c1867_5
  - python=3.7.12=hf930737_100_cpython
  - python-cdo=1.6.0=pyhd8ed1ab_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-libarchive-c=4.0=py37h89c1867_1
  - python_abi=3.7=4_cp37m
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=6.0=py37h540881e_4
  - pyzmq=24.0.1=py37h0c0c2a8_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.2=pyhd8ed1ab_0
  - ripgrep=14.1.1=h8fae777_1
  - ruamel_yaml=0.15.80=py37h540881e_1007
  - scipy=1.7.3=py37hf2a6cf1_0
  - setuptools=59.8.0=py37h89c1867_1
  - shapely=1.8.0=py37h9b0f7a3_4
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.46.0=h6d4b2fc_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.2=py37h540881e_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - udunits2=2.2.28=h40f5838_3
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wcwidth=0.2.10=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xarray=0.17.0=pyhd8ed1ab_0
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h75354e8_4
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.18.0=py37h540881e_0
  - zstd=1.5.6=ha6fb4c9_0
  - netcdf4
  - pip
  - pip:
      - alabaster==0.7.13
      - attrs==24.2.0
      - babel==2.14.0
      - basemap==1.4.1
      - basemap-data==1.3.2
      - cftime==1.6.2
      - click==8.1.8
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - docopt==0.6.2
      - docutils==0.19
      - exceptiongroup==1.3.0
      - fiona==1.9.6
      - imagesize==1.4.1
      - importlib-metadata==6.7.0
      - iniconfig==2.0.0
      - path==16.6.0
      - path-py==12.5.0
      - pluggy==1.2.0
      - pytest==7.4.4
      - snowballstemmer==3.0.1
      - sphinx==5.3.0
      - sphinx-rtd-theme==2.0.0
      - sphinxcontrib-applehelp==1.0.2
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - tomli==2.0.1
prefix: lagranto

